title: Resource Planner & Gantt for Jira
description: Documentation, support, privacy, and security information for Resource Planner & Gantt for Jira.
url: https://illiagryniuk.github.io
baseurl: /jira-resource-planner-legal
theme: minima
header_pages:
  - documentation.md
  - support.md
  - privacy-policy.md
  - security-statement.md
